name: GitHub Actions Example

# Controls when the workflow will run. On every push/pull_request run the whole workflow.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains build & test jobs
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  test: 
    name: GitHub Sample Testing
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run sample workflow
        uses: actions/checkout@v3
      - name: Running workflow
        run: echo Sample workflow running 

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: 
          echo Creating Sample Workflow,
          echo GitHub with Jira integration.
